{
  "headers": {
    "authorization": "1234",
    "clientid": "1234",
    "clientsecret": "1234",
    "x-correlation-id": "1234",
    "orchestration-type": "\"value\"",
    "user-agent": "PostmanRuntime/7.28.4",
    "accept": "*/*",
    "postman-token": "74086eb8-feb1-457a-8109-39888fa4218d",
    "host": "localhost:8082",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive"
  },
  "clientCertificate": null,
  "method": "GET",
  "scheme": "https",
  "queryParams": {},
  "requestUri": "/api/status",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/status",
  "listenerPath": "/api/*",
  "relativePath": "/api/status",
  "localAddress": "/127.0.0.1:8082",
  "uriParams": {},
  "rawRequestUri": "/api/status",
  "rawRequestPath": "/api/status",
  "remoteAddress": "/127.0.0.1:52575",
  "requestPath": "/api/status"
}