{
  "headers": {
    "x-correlation-id": "12121212",
    "username": "dad",
    "password": "dada",
    "user-agent": "PostmanRuntime/7.28.0",
    "accept": "*/*",
    "cache-control": "no-cache",
    "postman-token": "93e906ea-03bc-4966-aff7-d2f24a175ca6",
    "host": "localhost:8082",
    "accept-encoding": "gzip, deflate, br",
    "connection": "keep-alive"
  },
  "clientCertificate": null,
  "method": "GET",
  "scheme": "http",
  "queryParams": {},
  "requestUri": "/console",
  "queryString": "",
  "version": "HTTP/1.1",
  "maskedRequestPath": "/",
  "listenerPath": "/console/*",
  "relativePath": "/console",
  "localAddress": "/127.0.0.1:8082",
  "uriParams": {},
  "rawRequestUri": "/console",
  "rawRequestPath": "/console",
  "remoteAddress": "/127.0.0.1:50956",
  "requestPath": "/console"
}